<a href="https://colab.research.google.com/github/gulamkibria775/Data_science_project/blob/main/Data_science_project/Tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tf.version.VERSION   or print(tf.__version__)


'2.14.0'

In [ ]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
a=tf.constant(2)
b=tf.constant(5)
c=a+b
print(c)

Tensor("add:0", shape=(), dtype=int32)


In [ ]:
ssn=tf.compat.v1.Session()
ssn.run(c)

7

In [ ]:
x1=tf.constant([1,2,3,4,5])
x2=tf.constant([3,4,5,6,7])
result=x1*x2
print(result)
ssn.run(result)

Tensor("mul_2:0", shape=(5,), dtype=int32)


array([ 3,  8, 15, 24, 35], dtype=int32)

Placeholder : not providing values at the time of declaration but providing values later at the time of execution


In [ ]:
a=tf.compat.v1.placeholder(tf.float32)
b=tf.compat.v1.placeholder(tf.float32)
c=a+b
ssn.run(c,{a:10,b:20})

30.0

In [ ]:
ssn.run(c,{a:[1,2,3],b:[4,2,1]})

array([5., 4., 4.], dtype=float32)

Variable

In [ ]:
x=tf.compat.v1.Variable([1])
w=tf.compat.v1.Variable([3])
c=x*w
init=tf.compat.v1.global_variables_initializer()
ssn.run(init)
ssn.run(c)

array([3], dtype=int32)